### ISSUE TITLE
Is there a way to do batch classification within a pipeline?

### ISSUE THREAD

**Issue by raulgarreta** [monkeylearn/scrapy-monkeylearn#3]
It would be much faster to process items in batches of say 100 items.

**Comment by eudoxia0** [comment]
While that's a clear optimization, unfortunately because of the way Scrapy pipelines are designed that's not really possible.

The obvious approach would be accumulating the Items in an instance variable of the pipeline, then classifying every _n_ Items or once the end of the items is reached. Because objects in a scrapy pipeline go through each pipeline all at once (Like function composition, `p_1(p_2(p_3(item)))`), by the time we get a nice clean batch of Items, those items would be just copies of the original items which went their own way down the pipeline.

More complex approaches are essentially incompatible with pipelines, like having a Pipeline store items in the database, then classify the database objects which are persisted in the database, unlike Scrapy Items.

It might be worthwhile to investigate exactly how Items travel through the pipelines, or whether someone has had a similar problem where they want to do batch processing on Scrapy Items without reinventing the pipeline wheel.

**Comment by pablohoffman** [comment]
Batching would also help to avoid the errors we're getting now when users try the MonkeyLearn pipeline with the free plan which has this limitation (according to monkeylearn.com/faq):

> The free plan has a limit of 20 requests per minute that allow you to do up to 4,000 queries per minute.

In the example bestbuy crawler (`scrapinghub-addon-post`) this limit is exceeded right away.

I think this change should be introduced before we announce the integration, to avoid bad experiences with users.
